# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TForecast' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for TForecast
  pod 'Toast-Swift', '~> 5.1.1'
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'LookinServer', :subspecs => ['Swift'], :configurations => ['Debug']
  pod 'SwiftSpinner'
  pod 'Highcharts', '~> 11.1.0'
  
  post_install do |installer|
      installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
              end
          end
      end
  end
  
end
